### ISSUE TITLE
build/install

### ISSUE THREAD

**Issue by kitech** [childeYin/testim#2]
can build with `go build`

**Comment by childeYin** [comment]
yeah , thank you

**Comment by kitech** [comment]
$ sh ./server.sh start
./server.sh:行11: server.go: 未找到命令

got this.

**Comment by kitech** [comment]
$ ./client.sh filestart
2016/11/15 15:56:39 请输入邮箱:
abc@efg.com
2016/11/15 15:56:46 请输入密码:
hehehe
2016/11/15 15:56:51 程序终止!

got this.

**Comment by childeYin** [comment]
filestart, user's Info was stored in config.go, you can edit it
